# Generated by Django 3.0.6 on 2020-05-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='area_square_meters',
        ),
        migrations.AddField(
            model_name='city',
            name='area',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=15),
        ),
    ]
