# Generated by Django 3.0.6 on 2020-05-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='area_square_meters',
        ),
        migrations.AddField(
            model_name='branch',
            name='area',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=15),
        ),
    ]
