# Generated by Django 3.0.6 on 2020-05-23 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_auto_20200521_0208'),
        ('cities', '0002_auto_20200521_0151'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(default=True)),
                ('phone', models.PositiveIntegerField(default=None, verbose_name=10)),
                ('work_type', models.CharField(choices=[("('LA', 'LABOUR')", 'La'), ('IT', 'INFO TECH')], default="('LA', 'LABOUR')", max_length=16)),
                ('branch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.Branch')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities.City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
